### ISSUE TITLE
Error, plugin load hook should return a string.

### ISSUE THREAD

**Issue by trusktr** [erikdesjardins/webpack-rollup-loader#15]
I'm getting:

```js
ERROR in ./src/index.js
Module build failed: Error: Error loading node_modules/core-js/library/modules/es6.object.to-string.js: plugin load hook should return a string, a {
code, map } object, or nothing/null
    at error (/home/trusktr/Downloads/src/trusktr+infamous/node_modules/rollup/dist/rollup.js:170:15)
    at /home/trusktr/Downloads/src/trusktr+infamous/node_modules/rollup/dist/rollup.js:18742:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

My config looks like this:

```js
const path = require('path')
const babelConfig = require('./babel.config')
const bubleConfig = require('./buble.config')
const rollupConfig = require('./rollup.config.js')
const BabelMinify = require("babel-minify-webpack-plugin");

module.exports = {
    entry: './src/index.js',
    output: {
        path: __dirname,
        filename: 'global.js',
        library: 'infamous',
        libraryTarget: 'var', // alternative: "window"
    },
    module: {
        rules: [
            {
                test: /src\/index\.js$/,
                use: [{
                    loader: 'webpack-rollup-loader',
                    options: rollupConfig,
                }],
            },
            {
                test: /\.js$/,
                include: [
                    path.resolve(__dirname, 'src'),
                    path.resolve(__dirname, 'node_modules', '@awaitbox'), // ES6+
                    path.resolve(__dirname, 'node_modules', 'custom-attributes'), // ES6+
                ],
                use: [
                    {
                        loader: 'buble-loader',
                        options: bubleConfig,
                    },
                    {
                        loader: 'babel-loader',
                        options: Object.assign(babelConfig, {
                            //runtimeHelpers: true, // TODO: this is rollup plugin option. What's equivalent in babel-loader?
                        }),
                    },
                ],
            },
        ],
    },
    plugins: [
        new BabelMinify({}, {
            comments: false,
        })
    ],
}
```

where `rollupConfig` is this:

```js
const commonjs    = require('rollup-plugin-commonjs')

module.exports = {
    input: 'src/index.js',
    output: {
        name: 'infamous',
        file: 'global.js',
        format: 'iife',
    },
    plugins: [
        commonjs({
            exclude: [ 'src/**' ],
            include: [ 'node_modules/**' ],
        }),
    ]
};
```

Any ideas what it might be? I thought about putting `commonjs` rollup plugin because I need to import from node_modules, and they aren't all ES6 Modules.

**Comment by trusktr** [comment]
Ah, it's because `node_modules/core-js/library/modules/es6.object.to-string.js` is an empty file. Placing the word `undefined` inside of it fixes the problem. It all works!

**Comment by trusktr** [comment]
Ah, crap. Well, the same node_modules that were missing when using Rollup directly, are now still missing.

Screw it, I'm not using Rollup. I will live with Webpack's heavier output because..... **_it just works!_**

**Comment by frontendphil** [comment]
I don't have any further insights, but am facing the same error. We are consuming some library code that has empty `index.js` files (mostly these included flowtype annotations that were stripped by the transpiler, thus the empty file). 

I'd still be happy to get the setup working with this loader, because we're currently creating a `2.8mb` bundle to display a form, which is not great at all. However, I don't have a clue where to start looking for a solution.

**Comment by erikdesjardins** [comment]
Ah, I've actually encountered this problem before. With the exact same core-js file too. Why did I never fix it...

I believe this is a bug in rollup itself; it [tests the string for truthiness](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/Graph.ts#L518), so an empty string breaks it. I'll PR a fix. If it turns out that's intended, I'll add `source || ' '` to this.

(But yes, this is very much a hack. I should make that clear in the readme.)

**Comment by erikdesjardins** [comment]
https://github.com/rollup/rollup/pull/1908

**Comment by erikdesjardins** [comment]
(sorry about the delay, btw)

**Comment by erikdesjardins** [comment]
rollup 0.55.1 has the fix.
